name: Apply Patch from Comment
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write

jobs:
  apply-patch:
    if: contains(github.event.comment.body, '[apply-patch]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract patch from comment
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body;
            const match = body.match(/```patch([\\s\\S]*?)```/);
            if (!match) core.setFailed('No se encontró bloque ```patch``` en el comentario.');
            core.setOutput('patch', match[1].trim());
      - name: Write patch file
        run: echo "${{ steps.extract.outputs.patch }}" > changes.patch
      - name: Create branch
        run: |
          BRANCH="chatgpt/patch-${{ github.run_id }}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git switch -c "$BRANCH"
      - name: Apply patch (3-way)
        run: |
          git apply --whitespace=fix --3way changes.patch || (echo "::error::Falló git apply" && exit 1)
          git add -A
          git commit -m "Apply patch from comment by ${{ github.actor }}"
          git push -u origin "$BRANCH"
      - name: Open PR
        uses: actions/github-script@v7
        with:
          script: |
            const branch = process.env.BRANCH;
            const { data: repo } = await github.repos.get(context.repo);
            const base = repo.default_branch;
            const pr = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Apply patch ${branch}`,
              head: branch,
              base,
              body: `Parche aplicado automáticamente desde comentario por @${context.actor}.`
            });
            core.notice(`PR creado: #${pr.data.number}`);
